Increase flexibility of bruteforce signature extration
mailgun/talon pull request #166
Opened 2018-05-16 09:27 UTC by RonRademaker

Allows overriding line length, max line length (useful if you expect disclaimers) and greetings (useful from a language perspective) when extracting signatures bruteforce

2018-08-07 07:48 UTC, obukhov-sergey commented
@mailgun-ci test this please

2018-08-07 08:08 UTC, obukhov-sergey reviewed
Lgtm, minor comments, syntax error fails tests

2018-08-07 08:08 UTC, obukhov-sergey commented on talon/signature/extractor.py
> +Module with object oriented approach to
Out of curiosity - why the comment lines are so short? I know shorter lines are easier to read but usually 80 chars is ok. Functions that go on for many lines become hard to read just like lines stretching for many chars.

2018-08-14 08:18 UTC, RonRademaker commented
Thanks for the feedback, I processed it

2018-11-02 09:21 UTC, obukhov-sergey commented
@mailgun-ci test this please

2018-11-02 11:21 UTC, obukhov-sergey commented
@RonRademaker sorry for delay with the merge, can you plz add abc to setup.py to make tests pass?

2018-11-02 11:23 UTC, obukhov-sergey requested changes
Tests fail with ```ImportError: cannot import name ABC```. Plz add abc to setup.py.

2018-11-02 11:52 UTC, RonRademaker commented
Any way I can locally run the tests to see if they pass before pushing changes?

2018-11-05 07:45 UTC, obukhov-sergey commented
@mailgun-ci test this please

2018-11-05 07:48 UTC, obukhov-sergey commented
@RonRademaker sure, just run nosetests from the repo folder, you might need to "pip install nose" and "pip install mock", they're also in test_require part of setup.py; we plan to migrate to travis ci as well, so that you don't have to run tests yourself locally.

2026-09-05 21:22 UTC, obukhov-sergey commented
Closing as there was no activity on the PR for a while.

2026-09-05 21:22 UTC, closed without merging